package thelm.wrapup;

import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLLoadCompleteEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import net.minecraftforge.fml.common.eventhandler.EventPriority;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.VillagerRegistry.VillagerProfession;
import thelm.wrapup.event.InitializationWrapUpEvent;
import thelm.wrapup.event.LoadCompleteWrapUpEvent;
import thelm.wrapup.event.PostInitializationWrapUpEvent;
import thelm.wrapup.event.PreInitializationWrapUpEvent;
import thelm.wrapup.event.RegistryWrapUpEvent;
import thelm.wrapup.event.ServerStartingWrapUpEvent;

@Mod(
		modid = WrapUp.MOD_ID,
		name = WrapUp.NAME,
		version = WrapUp.VERSION,
		acceptedMinecraftVersions = "[1.10,1.12)",
		dependencies = "after:*"
		)
public class WrapUp {

	public static final String MOD_ID = "wrapup";
	public static final String NAME = "WrapUp";
	public static final String VERSION = "1.10.2-1.0.2";
	public static final WrapUp INSTANCE = new WrapUp();;
	public static ModMetadata metadata;

	static {
		MinecraftForge.EVENT_BUS.register(INSTANCE);
	}

	@EventHandler
	public void firstMovement(FMLPreInitializationEvent event) {
		metadata = event.getModMetadata();
		metadata.autogenerated = false;
		metadata.version = VERSION;
		metadata.authorList.add("TheLMiffy1111");
		metadata.description = "A mod to wrap up initializations.";
		
		MinecraftForge.EVENT_BUS.post(new PreInitializationWrapUpEvent.Event0(event));
		MinecraftForge.EVENT_BUS.post(new PreInitializationWrapUpEvent.Event1(event));
		MinecraftForge.EVENT_BUS.post(new PreInitializationWrapUpEvent.Event2(event));
		MinecraftForge.EVENT_BUS.post(new PreInitializationWrapUpEvent.Event3(event));
		MinecraftForge.EVENT_BUS.post(new PreInitializationWrapUpEvent.Event4(event));
	}

	@EventHandler
	public void secondMovement(FMLInitializationEvent event) {
		MinecraftForge.EVENT_BUS.post(new InitializationWrapUpEvent.Event0(event));
		MinecraftForge.EVENT_BUS.post(new InitializationWrapUpEvent.Event1(event));
		MinecraftForge.EVENT_BUS.post(new InitializationWrapUpEvent.Event2(event));
		MinecraftForge.EVENT_BUS.post(new InitializationWrapUpEvent.Event3(event));
		MinecraftForge.EVENT_BUS.post(new InitializationWrapUpEvent.Event4(event));
	}

	@EventHandler
	public void thirdMovement(FMLPostInitializationEvent event) {
		MinecraftForge.EVENT_BUS.post(new PostInitializationWrapUpEvent.Event0(event));
		MinecraftForge.EVENT_BUS.post(new PostInitializationWrapUpEvent.Event1(event));
		MinecraftForge.EVENT_BUS.post(new PostInitializationWrapUpEvent.Event2(event));
		MinecraftForge.EVENT_BUS.post(new PostInitializationWrapUpEvent.Event3(event));
		MinecraftForge.EVENT_BUS.post(new PostInitializationWrapUpEvent.Event4(event));
	}

	@EventHandler
	public void fourthMovement(FMLLoadCompleteEvent event) {
		MinecraftForge.EVENT_BUS.post(new LoadCompleteWrapUpEvent.Event0(event));
		MinecraftForge.EVENT_BUS.post(new LoadCompleteWrapUpEvent.Event1(event));
		MinecraftForge.EVENT_BUS.post(new LoadCompleteWrapUpEvent.Event2(event));
		MinecraftForge.EVENT_BUS.post(new LoadCompleteWrapUpEvent.Event3(event));
		MinecraftForge.EVENT_BUS.post(new LoadCompleteWrapUpEvent.Event4(event));
	}

	@EventHandler
	public void fifthMovement(FMLServerStartingEvent event) {
		MinecraftForge.EVENT_BUS.post(new ServerStartingWrapUpEvent.Event0(event));
		MinecraftForge.EVENT_BUS.post(new ServerStartingWrapUpEvent.Event1(event));
		MinecraftForge.EVENT_BUS.post(new ServerStartingWrapUpEvent.Event2(event));
		MinecraftForge.EVENT_BUS.post(new ServerStartingWrapUpEvent.Event3(event));
		MinecraftForge.EVENT_BUS.post(new ServerStartingWrapUpEvent.Event4(event));
	}

	@SubscribeEvent(priority = EventPriority.LOWEST)
	public void onVillagerProfessionRegisterLowest(RegistryEvent.Register<VillagerProfession> event) {
		MinecraftForge.EVENT_BUS.post(new RegistryWrapUpEvent.Event0());
		MinecraftForge.EVENT_BUS.post(new RegistryWrapUpEvent.Event1());
		MinecraftForge.EVENT_BUS.post(new RegistryWrapUpEvent.Event2());
		MinecraftForge.EVENT_BUS.post(new RegistryWrapUpEvent.Event3());
		MinecraftForge.EVENT_BUS.post(new RegistryWrapUpEvent.Event4());
	}
}
